# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ohash}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fabian Streitel"]
  s.date = %q{2009-08-05}
  s.description = %q{A simple, enhanced hash structure with the direct member access of OpenStruct, but without all the restrictions.}
  s.email = %q{karottenreibe@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.markdown"
  ]
  s.files = [
    "HISTORY.markdown",
     "LICENSE.txt",
     "Manifest.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/ohash.rb",
     "ohash.gemspec"
  ]
  s.homepage = %q{http://github.com/karottenreibe/vim-syntax}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ohash}
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{A simple, enhanced hash structure with the direct member access of OpenStruct, but without all the restrictions.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
